### ISSUE TITLE
Integrate morgan library 

### ISSUE THREAD

**Issue by Aman-Codes** [webevaluator/nodebackend#5]
# Description
Integrate morgan library with [log file rotation](https://www.npmjs.com/package/morgan#log-file-rotation) to the project. The library should write logs to one file per day inside the `/logs` directory. Also add the `/logs` directory to `.gitignore`, `.dockerignore`, `.eslintignore` and `.prettierignore`.

**Comment by digvijayyanand** [comment]
Can I work on this?

**Comment by Aman-Codes** [comment]
Go ahead @digvijayyanand
